using PlServer.LegacyProtocol;
using PlServer.Session;

namespace PlServer.Application;

public sealed class LoginRequestCandidateHandler : IActionHandler
{
    private readonly LoginRequestCandidateParserRegistry parserRegistry;
    private readonly LoginResponseCandidatePlanner responsePlanner;
    private readonly CharacterListCandidatePlanner characterListPlanner;

    public LoginRequestCandidateHandler()
        : this(
            LoginRequestCandidateParserRegistry.CreateDefault(),
            new LoginResponseCandidatePlanner(),
            new CharacterListCandidatePlanner())
    {
    }

    public LoginRequestCandidateHandler(LoginRequestCandidateParserRegistry parserRegistry)
        : this(
            parserRegistry,
            new LoginResponseCandidatePlanner(),
            new CharacterListCandidatePlanner())
    {
    }

    public LoginRequestCandidateHandler(
        LoginRequestCandidateParserRegistry parserRegistry,
        LoginResponseCandidatePlanner responsePlanner)
        : this(
            parserRegistry,
            responsePlanner,
            new CharacterListCandidatePlanner())
    {
    }

    public LoginRequestCandidateHandler(
        LoginRequestCandidateParserRegistry parserRegistry,
        LoginResponseCandidatePlanner responsePlanner,
        CharacterListCandidatePlanner characterListPlanner)
    {
        this.parserRegistry = parserRegistry ?? throw new ArgumentNullException(nameof(parserRegistry));
        this.responsePlanner = responsePlanner ?? throw new ArgumentNullException(nameof(responsePlanner));
        this.characterListPlanner = characterListPlanner ?? throw new ArgumentNullException(nameof(characterListPlanner));
    }

    public string HandlerName => nameof(LoginRequestCandidateHandler);

    public bool CanHandle(LegacyProtocolContract contract)
    {
        ArgumentNullException.ThrowIfNull(contract);
        return contract.ProtocolName == "LoginRequestCandidate";
    }

    public ValueTask<ActionRouteResult> HandleAsync(
        ActionRouteRequest request,
        LegacyProtocolContract contract,
        SessionPacketKind packetKind,
        SessionStateGuardResult sessionGuardResult,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(contract);
        ArgumentNullException.ThrowIfNull(sessionGuardResult);

        cancellationToken.ThrowIfCancellationRequested();

        var context = new ActionHandlerContext(request, contract, packetKind, sessionGuardResult);
        var parseResult = parserRegistry.Parse(context);
        var responsePlan = responsePlanner.Plan(
            parseResult,
            authenticationResult: null,
            request.SessionState);
        var characterListPlan = characterListPlanner.Plan(
            responsePlan,
            authenticationResult: null,
            request.SessionState);
        var notes = new List<string>
        {
            "login request candidate-only handler invoked",
            "pending target-client trace",
            "payload kept opaque; no account authentication performed",
            "account repository not invoked because login field layout is unknown",
            "no login response packet generated",
            "no character list generated",
            $"parser status: {parseResult.Status}",
            $"parser source: {parseResult.SourceLabel}",
            $"parser evidence status: {parseResult.EvidenceStatus}",
            $"parser is confirmed: {parseResult.IsConfirmed}",
            $"parser payload length: {parseResult.PayloadLength}",
            $"response planning status: {responsePlan.Status}",
            $"response plan should generate packet: {responsePlan.ShouldGeneratePacket}",
            $"response plan is confirmed: {responsePlan.IsConfirmed}",
            $"response plan evidence status: {responsePlan.EvidenceStatus}",
            $"character list planning status: {characterListPlan.Status}",
            $"character list should generate packet: {characterListPlan.ShouldGeneratePacket}",
            $"character list plan is confirmed: {characterListPlan.IsConfirmed}",
            $"character list evidence status: {characterListPlan.EvidenceStatus}",
            "response candidate planning completed without generated bytes",
            "character list response not generated",
            "no character selection response generated",
            "no enter-map response generated",
            "no response generated"
        };
        notes.AddRange(parseResult.Notes);
        notes.AddRange(responsePlan.Notes);
        notes.AddRange(characterListPlan.Notes);

        var handlerResult = new ActionHandlerResult(
            HandlerName,
            ActionHandlerStatus.CandidateHandled,
            notes);

        return ValueTask.FromResult(ActionRouteResult.FromHandler(
            contract,
            packetKind,
            sessionGuardResult,
            request.PacketDecodeResult.ValidationErrors,
            handlerResult));
    }
}
